var cardCategories = [
	"Appliance",
	"Beer",
	"Board Game",
	"Brand",
	"Chain Restaurant",
	"City",
	"Condiment",
	"Deity",
	"Dinosaur",
	"Disease",
	"Facial Hair",
	"Halloween Costume",
	"Holiday Item",
	"Jewelry",
	"Nut",
	"Reason to Celebrate",
	"Stackable Item",
	"Swear Word",
	"Tea",
	"Texting Shorthand",
	"Thanksgiving Dish",
	"Tool",
	"Transportation",
	"Vacation Spot",
	"Weapon",
	"Crime",
	"Hobby",
	"Adhesive",
	"Bird",
	"Book Genre",
	"Celebrity",
	"Chinese Zodiac",
	"Clothing Accessory",
	"Cocktail",
	"Drug",
	"Fabric",
	"Fictional Princess",
	"Food Allergy",
	"French Word",
	"Gem",
	"Hairstyle",
	"High School Insecurity",
	"Military Rank",
	"Movie Sequel",
	"Organ",
	"Pattern",
	"Pepper",
	"Porn Search Term",
	"Sitcom",
	"Soup",
	"Spice",
	"Tropical Fruit",
	"Foreign Word for Cheers",
	"Alliteration",
	"Amusement Park",
	"Bone",
	"Comedian",
	"Cut of Meat",
	"Drinking Game",
	"Fairy Tale",
	"Famous Rivalry",
	"Font",
	"Freak",
	"Gun",
	"Headpiece",
	"Internet Meme",
	"Island",
	"Item in a pocket",
	"Mafia Movie",
	"Mascot",
	"Ninja Gear",
	"Playground Game",
	"Rhyme",
	"Sex Position",
	"Torture Method",
	"Tree",
	"Unit of Measure",
	"Wine Varietal",
	"Word that starts with X",
	"African Country",
	"Architectural Feat",
	"Award Ceremony",
	"Broadway Musical",
	"Carnival Game",
	"Charcuterie",
	"Child Star",
	"Constellation",
	"Dead Ruler",
	"Dictator",
	"Famous Dwarf",
	"Famous Statue",
	"Fictional Land",
	"Fictional Race",
	"Horror Character",
	"Jewish Word",
	"Medieval Weapon",
	"Muscle",
	"Nursery Rhyme",
	"Prophet",
	"Punk Band",
	"Sci-Fi Author",
	"Slogan",
	"Stone",
	"Villain"
];

var cardSyms = Array.from(Array(104).keys()).map(i => Math.floor(i / 13));